sort:
  sections: mixed
nav:
  - Tehtävät:
    - Aloitussivu: 'koodi/koodi_toc.md'
    - "koodi/haasteet/*.md"
  - Apufunktiot: 
    - Aloitussivu: 'koodi/apufunktiot.md'
    - "koodi/apufunktiot/*.md"
  - Komentorivi:
    - 'tol-alkeet/index.md'
    - Tietokoneen käytön perusteet:
      - 'tol-alkeet/intro/tiedostot.md'
      - 'tol-alkeet/intro/perustiedostot.md'
      - 'tol-alkeet/intro/email.md'
    - Komentorivin alkeet:
      - 'tol-alkeet/komentorivi/bash-alkeet.md'
      - 'tol-alkeet/komentorivi/peruskomennot'
      - 'tol-alkeet/komentorivi/bash-muoto.md'
      - 'tol-alkeet/komentorivi/tiedostonimet.md'
      - 'tol-alkeet/komentorivi/asennus.md'
    - Komentorivin tehokäyttö:
      - 'tol-alkeet/komentorivin-jatkoa/komentosarjat'
      - 'tol-alkeet/komentorivin-jatkoa/ohjausrakenteet'
      - 'tol-alkeet/komentorivin-jatkoa/ymparisto.md'
    - "Muuta":
      - 'tol-alkeet/ascii.md'
      - 'tol-alkeet/glossaari.md'
  - Muuta:
    - Muita ideoita: 'koodi/muut_sivut/muut_sivut.md'

ignore:
  - "*.hidden.md"
