nav:
  - Tehtävät:
    - Aloitussivu: 'koodi/koodi_toc.md'
    - "koodi/haasteet/*.md"
  - Apufunktiot: 
    - Aloitussivu: 'koodi/apufunktiot.md'
    - "koodi/apufunktiot/*.md"
  - Komentorivi:
    - Aloitussivu: 'unix/intro.md'
    - "unix/*.md"
  - Muuta:
    - Muita ideoita: 'koodi/muut_sivut/muut_sivut.md'

ignore:
  - "*.hidden.md"